### ISSUE TITLE
Insert function is incorrect

### ISSUE THREAD

**Issue by StephenAmar** [runongirlrunon/assignment-3-totally-sucks#1]
I don't think the if block at line 102 (in the insert function) is doing what you want it to do.
As far as I can tell, it's corrupting the linked list.

**Comment by runongirlrunon** [comment]
Thank you for pointing that out! I updated the insert function to fix it. I think I broke my reverse function in doing that, though. Getting a really weird error now that I haven’t seen before. But I consider that progress! Haha. Thank you again.
